groups:
- name: my_websites
  rules:
  - alert: website_gone_to_heaven
    expr: probe_http_status_code == 0
    for: 10s
    labels:
      severity: page
    # Prometheus templates apply here in the annotation and label fields of the alert.
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
#      summary: 'Instance {{ $labels.instance }} down'- name: my_websites

- name: my_windows_turds
  rules:
  - alert: windows_agent_down
    expr: up{job="Windows_exporters"}==0
    for: 10s
    labels:
      severity: page
    # Prometheus templates apply here in the annotation and label fields of the alert.
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
#      summary: 'Instance {{ $labels.instance }} down'- name: my_windows_turds
